//! Request/response messages for kernel-routed plugin calls.
//!
//! `Call` is distinct from `Event`: point-to-point (single handler, not
//! broadcast), not subject to bus claim/cascade semantics, not written to
//! `event_log`, and its handler returns exactly one `CallResponse`.
//!
//! Some `Call` variants are **streaming** — their payload carries an
//! `mpsc::Sender` the handler writes items to during execution. The Call still
//! returns a single `CallResponse` (typically a summary) on completion.

use std::collections::HashMap;

use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;

use crate::capability_map::CapabilityMap;
use crate::compiled::CompiledPolicy;
use crate::evaluation::EvaluationOutcome;
use crate::events::{FileDiscoveredEvent, RootWalkCompletedEvent};
use crate::media::MediaFile;
use crate::plan::{PhaseOutput, Plan};
use crate::scan::ScanOptions;
use crate::transition::ScanSessionId;

/// A request addressed to exactly one plugin via its capability.
#[non_exhaustive]
#[derive(Debug)]
pub enum Call {
    /// Evaluate a compiled policy against a media file. Unary Call.
    EvaluatePolicy {
        policy: CompiledPolicy,
        file: MediaFile,
        phase: Option<String>,
        phase_outputs: Option<HashMap<String, PhaseOutput>>,
        phase_outcomes: Option<HashMap<String, EvaluationOutcome>>,
        capabilities_override: Option<CapabilityMap>,
    },
    /// Orchestrate phases from pre-evaluated plans. Unary Call.
    Orchestrate {
        plans: Vec<Plan>,
        policy_name: String,
    },
    /// Streaming Call: scan a library root and emit a `FileDiscoveredEvent` to
    /// `sink` for each file found. Returns a summary on completion. The plugin
    /// checks `cancel` between items and exits early when cancelled. If
    /// `root_done` is `Some`, the plugin sends a `RootWalkCompletedEvent` there
    /// **only after a successful scan**, carrying the caller's `scan_session`.
    ///
    /// Non-serde fields (`sink`, `root_done`, `cancel`) are in-process resources;
    /// WASM plugins access equivalent functionality via host fns (Phase 2).
    /// `scan_session` is the caller's session id — used by the gate logic
    /// downstream to associate events with the right scan run. Generated by
    /// the CLI (whether or not the command uses gate semantics).
    ScanLibrary {
        uri: String,
        options: ScanOptions,
        scan_session: ScanSessionId,
        sink: mpsc::Sender<FileDiscoveredEvent>,
        root_done: Option<mpsc::Sender<RootWalkCompletedEvent>>,
        cancel: CancellationToken,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiled::{CompiledConfig, CompiledMetadata, ErrorStrategy};
    use std::path::PathBuf;

    /// Construct a minimal `CompiledPolicy` directly via its public
    /// constructors. We deliberately avoid `voom_dsl::compile_policy` here:
    /// adding `voom-dsl` as a dev-dependency would create two distinct
    /// instances of `voom-domain` in the test binary (voom-dsl re-exports
    /// CompiledPolicy from voom-domain, so types fail to unify).
    fn minimal_policy() -> CompiledPolicy {
        CompiledPolicy::new(
            "demo".into(),
            CompiledMetadata::default(),
            CompiledConfig::new(vec![], vec![], ErrorStrategy::Abort, vec![], false),
            vec![],
            vec![],
            String::new(),
        )
    }

    #[test]
    fn evaluate_policy_call_constructs() {
        let call = Call::EvaluatePolicy {
            policy: minimal_policy(),
            file: MediaFile::new(PathBuf::from("/x.mkv")),
            phase: None,
            phase_outputs: None,
            phase_outcomes: None,
            capabilities_override: None,
        };
        let dbg = format!("{call:?}");
        assert!(dbg.contains("EvaluatePolicy"));
    }

    #[test]
    fn orchestrate_call_constructs() {
        let call = Call::Orchestrate {
            plans: vec![],
            policy_name: "demo".into(),
        };
        let dbg = format!("{call:?}");
        assert!(dbg.contains("Orchestrate"));
    }

    #[test]
    fn scan_library_call_constructs() {
        let (sink, _rx) = mpsc::channel::<FileDiscoveredEvent>(8);
        let (root_done, _rx_done) = mpsc::channel::<RootWalkCompletedEvent>(8);
        let cancel = CancellationToken::new();
        let call = Call::ScanLibrary {
            uri: "file:///tmp/test".into(),
            options: ScanOptions::new("/tmp/test"),
            scan_session: ScanSessionId::new(),
            sink,
            root_done: Some(root_done),
            cancel,
        };
        let dbg = format!("{call:?}");
        assert!(dbg.contains("ScanLibrary"));
    }
}
