use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::Context;
use anyhow::Result;

use crate::cli::BugReportUploadArgs;

pub fn run(args: BugReportUploadArgs) -> Result<()> {
    let body = build_issue_body(&args.report_dir)?;
    let body_file = write_temp_body(&args.report_dir, &body)?;
    let issue = args.issue.to_string();
    let status = Command::new("gh")
        .args([
            "issue",
            "comment",
            &issue,
            "--repo",
            &args.repo,
            "--body-file",
        ])
        .arg(&body_file)
        .status()
        .context(
            "failed to run `gh issue comment`; install GitHub CLI and authenticate with `gh auth login`",
        );

    // Upload can still report the `gh` failure if temporary-file cleanup fails.
    let _ = std::fs::remove_file(&body_file);
    let status = status?;

    if !status.success() {
        anyhow::bail!("`gh issue comment` failed with status {status}");
    }

    Ok(())
}

fn build_issue_body(report_dir: &Path) -> Result<String> {
    let report_path = report_dir.join("report.md");
    let report = std::fs::read_to_string(&report_path)
        .with_context(|| format!("failed to read {}", report_path.display()))?;
    Ok(format!(
        "{report}\n\n---\nGenerated by `voom bug-report generate`. \
         `report.json` remains local unless manually attached by the reporter.\n"
    ))
}

fn write_temp_body(report_dir: &Path, body: &str) -> Result<PathBuf> {
    let path = upload_body_path(report_dir);
    std::fs::write(&path, body).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(path)
}

fn upload_body_path(report_dir: &Path) -> PathBuf {
    let mut path = std::env::temp_dir();
    let report_name = report_dir
        .file_name()
        .and_then(std::ffi::OsStr::to_str)
        .unwrap_or("report");
    path.push(format!(
        "voom-bug-report-{report_name}-{}.md",
        std::process::id()
    ));
    path
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn upload_body_uses_only_sanitized_files() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("report.md"), "sanitized video000.mkv").unwrap();
        std::fs::write(
            dir.path().join("redactions.local.json"),
            r#"[{"original":"The Movie (2026).mkv"}]"#,
        )
        .unwrap();

        let body = build_issue_body(dir.path()).unwrap();

        assert!(body.contains("sanitized video000.mkv"));
        assert!(!body.contains("The Movie"));
    }

    #[test]
    fn upload_rejects_missing_report_md() {
        let dir = tempfile::tempdir().unwrap();
        let err = build_issue_body(dir.path()).unwrap_err();

        assert!(err.to_string().contains("report.md"));
    }

    #[test]
    fn upload_body_temp_file_is_outside_report_dir() {
        let dir = tempfile::tempdir().unwrap();
        let path = upload_body_path(dir.path());

        assert!(!path.starts_with(dir.path()));
        assert_eq!(
            path.extension().and_then(std::ffi::OsStr::to_str),
            Some("md")
        );
    }
}
