//! Functional test suite — end-to-end tests exercising the `voom` CLI binary
//! against real media files generated by `scripts/generate-test-corpus`.
//!
//! Gated behind `#[cfg(feature = "functional")]` so they never run during
//! normal `cargo test`. Invoke with:
//!
//! ```bash
//! cargo test -p voom-cli --features functional -- --test-threads=4
//! ```
//!
//! **Requirements**: `python3` and `ffmpeg` on PATH for corpus generation.
//! Individual tests may also require `ffprobe`, `mkvmerge`, or `mkvpropedit`.

#![cfg(feature = "functional")]

use assert_cmd::Command;
use predicates::prelude::*;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

// ═══════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════

/// Check if a tool is available on PATH.
fn has_tool(name: &str) -> bool {
    std::process::Command::new("which")
        .arg(name)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Skip the current test if the named tool is not on PATH.
macro_rules! require_tool {
    ($tool:expr) => {
        if !has_tool($tool) {
            eprintln!("SKIPPED: {} not found on PATH", $tool);
            return;
        }
    };
}

/// A self-contained test environment with isolated config and data dirs.
struct TestEnv {
    _tempdir: tempfile::TempDir,
    config_home: PathBuf,
    voom_dir: PathBuf,
}

impl TestEnv {
    /// Create a new isolated environment with a minimal config.toml.
    fn new() -> Self {
        let tempdir = tempfile::tempdir().expect("create tempdir");
        let config_home = tempdir.path().join("config");
        let voom_dir = config_home.join("voom");
        std::fs::create_dir_all(&voom_dir).expect("create voom config dir");

        let config_toml = format!("data_dir = {:?}\n", voom_dir.display().to_string());
        let config_path = voom_dir.join("config.toml");
        std::fs::write(&config_path, &config_toml).expect("write config.toml");

        // Set restrictive permissions to avoid the "loose permissions" tracing warning
        // that would pollute stdout.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&config_path, std::fs::Permissions::from_mode(0o600))
                .expect("set config.toml permissions");
        }

        TestEnv {
            _tempdir: tempdir,
            config_home,
            voom_dir,
        }
    }

    /// Return an `assert_cmd::Command` with isolated config via `XDG_CONFIG_HOME`.
    fn voom(&self) -> Command {
        let mut cmd = Command::cargo_bin("voom").expect("binary exists");
        cmd.env("XDG_CONFIG_HOME", &self.config_home);
        cmd.env("NO_COLOR", "1");
        cmd
    }

    /// Path to the media directory inside this environment.
    fn media_dir(&self) -> PathBuf {
        self._tempdir.path().join("media")
    }

    /// Copy specific corpus files (by stem) into this environment's media dir.
    /// Pass an empty slice to copy all files.
    fn populate_media(&self, stems: &[&str]) {
        let corpus = corpus_dir();
        let media = self.media_dir();
        std::fs::create_dir_all(&media).expect("create media dir");
        for entry in std::fs::read_dir(corpus).expect("read corpus dir") {
            let entry = entry.expect("dir entry");
            if !entry.path().is_file() {
                continue;
            }
            let name = entry.file_name();
            let name_str = name.to_string_lossy();
            if stems.is_empty() {
                std::fs::copy(entry.path(), media.join(&*name_str)).expect("copy file");
                continue;
            }
            let stem = Path::new(&*name_str)
                .file_stem()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_default();
            if stems.iter().any(|s| *s == stem) {
                std::fs::copy(entry.path(), media.join(&*name_str)).expect("copy file");
            }
        }
    }

    /// Write a test policy file and return its path.
    fn write_policy(&self, name: &str, content: &str) -> PathBuf {
        let path = self.voom_dir.join(format!("{name}.voom"));
        std::fs::write(&path, content).expect("write policy");
        path
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Corpus generation (once per test run)
// ═══════════════════════════════════════════════════════════════════════════

static CORPUS: OnceLock<PathBuf> = OnceLock::new();

/// Get the path to the shared corpus directory, generating it on first call.
fn corpus_dir() -> &'static Path {
    CORPUS
        .get_or_init(|| {
            let dir = tempfile::tempdir().expect("create corpus tempdir");
            let path = dir.path().to_path_buf();
            // Leak so the dir lives for the entire process
            std::mem::forget(dir);

            let script = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("../../scripts/generate-test-corpus");

            assert!(
                script.exists(),
                "generate-test-corpus not found at {}",
                script.display()
            );

            let status = std::process::Command::new("python3")
                .arg(&script)
                .arg(&path)
                .arg("--duration")
                .arg("2")
                .arg("--seed")
                .arg("42")
                // Skip files needing rare encoders to keep CI green
                .arg("--skip")
                .arg("av1-opus,hevc-truehd")
                .status()
                .expect("run generate-test-corpus");

            if !status.success() {
                eprintln!(
                    "WARNING: generate-test-corpus had failures (exit {:?})",
                    status.code()
                );
            }

            assert!(
                path.join("basic-h264-aac.mp4").exists(),
                "corpus generation failed: basic-h264-aac.mp4 not found in {}",
                path.display()
            );

            path
        })
        .as_path()
}

/// Simple test policy for process tests.
const TEST_POLICY: &str = r#"
policy "test-normalize" {
  config {
    languages audio: [eng, und]
    languages subtitle: [eng, und]
    on_error: continue
  }

  phase normalize {
    keep audio where lang in [eng, und]
    keep subtitles where lang in [eng, und]

    defaults {
      audio: first_per_language
      subtitle: none
    }
  }
}
"#;

// ═══════════════════════════════════════════════════════════════════════════
// test_init
// ═══════════════════════════════════════════════════════════════════════════

mod test_init {
    use super::*;

    #[test]
    fn init_creates_config_and_dirs() {
        let env = TestEnv::new();
        // Remove the auto-created config so init has work to do
        std::fs::remove_dir_all(&env.voom_dir).unwrap();

        env.voom().arg("init").assert().success();

        assert!(env.voom_dir.join("config.toml").exists());
        assert!(env.voom_dir.join("policies").exists());
        assert!(env.voom_dir.join("policies/default.voom").exists());
    }

    #[test]
    fn init_is_idempotent() {
        let env = TestEnv::new();
        std::fs::remove_dir_all(&env.voom_dir).unwrap();

        env.voom().arg("init").assert().success();
        env.voom()
            .arg("init")
            .assert()
            .success()
            .stdout(predicate::str::contains("already exists"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_doctor
// ═══════════════════════════════════════════════════════════════════════════

mod test_doctor {
    use super::*;

    #[test]
    fn doctor_reports_health() {
        let env = TestEnv::new();
        env.voom()
            .arg("doctor")
            .assert()
            .success()
            .stdout(predicate::str::contains("Database"))
            .stdout(predicate::str::contains("External tools"))
            .stdout(predicate::str::contains("Plugins"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_scan
// ═══════════════════════════════════════════════════════════════════════════

mod test_scan {
    use super::*;

    #[test]
    fn scan_discovers_media_files() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac", "hevc-surround"]);

        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success()
            .stdout(predicate::str::contains("2 files discovered"));
    }

    #[test]
    fn scan_with_no_hash() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac"]);

        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap(), "--no-hash"])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success()
            .stdout(predicate::str::contains("hashing skipped"));
    }

    #[test]
    fn scan_empty_directory() {
        let env = TestEnv::new();
        std::fs::create_dir_all(env.media_dir()).unwrap();

        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .assert()
            .success()
            .stdout(predicate::str::contains("No media files found"));
    }

    #[test]
    fn scan_nonexistent_path_fails() {
        let env = TestEnv::new();
        env.voom()
            .args(["scan", "/nonexistent/path/to/media"])
            .assert()
            .failure();
    }

    #[test]
    fn scan_populates_database() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac"]);

        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        env.voom()
            .arg("status")
            .assert()
            .success()
            .stdout(predicate::str::contains("1 files"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_inspect
// ═══════════════════════════════════════════════════════════════════════════

mod test_inspect {
    use super::*;

    #[test]
    fn inspect_shows_metadata() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["hevc-surround"]);
        let file = env.media_dir().join("hevc-surround.mkv");

        env.voom()
            .args(["inspect", file.to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(30))
            .assert()
            .success()
            .stdout(
                predicate::str::contains("hevc")
                    .or(predicate::str::contains("h265"))
                    .or(predicate::str::contains("HEVC")),
            );
    }

    #[test]
    fn inspect_json_format() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac"]);
        let file = env.media_dir().join("basic-h264-aac.mp4");

        // Scan first so the file is in the DB (avoids "introspecting..." prefix in output)
        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        let output = env
            .voom()
            .args(["inspect", file.to_str().unwrap(), "--format", "json"])
            .timeout(std::time::Duration::from_secs(30))
            .output()
            .expect("run inspect");

        assert!(output.status.success());
        let stdout = String::from_utf8_lossy(&output.stdout);
        let _: serde_json::Value =
            serde_json::from_str(&stdout).expect("inspect --format json should produce valid JSON");
    }

    #[test]
    fn inspect_from_database_after_scan() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac"]);
        let file = env.media_dir().join("basic-h264-aac.mp4");

        // Scan first to populate DB
        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        // Inspect should hit DB (no "introspecting" message)
        env.voom()
            .args(["inspect", file.to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(30))
            .assert()
            .success()
            .stdout(predicate::str::contains("introspecting").not());
    }

    #[test]
    fn inspect_multitrack_file() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["hevc-surround"]);
        let file = env.media_dir().join("hevc-surround.mkv");

        // hevc-surround.mkv: 1 video, 2 audio (ac3 + aac), 2 subtitles
        env.voom()
            .args(["inspect", file.to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(30))
            .assert()
            .success()
            .stdout(
                predicate::str::contains("ac3")
                    .or(predicate::str::contains("aac"))
                    .or(predicate::str::contains("Audio")),
            );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_process
// ═══════════════════════════════════════════════════════════════════════════

mod test_process {
    use super::*;

    #[test]
    fn process_dry_run() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["hevc-surround"]);
        let policy = env.write_policy("test", TEST_POLICY);

        env.voom()
            .args([
                "process",
                env.media_dir().to_str().unwrap(),
                "--policy",
                policy.to_str().unwrap(),
                "--dry-run",
            ])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success()
            .stdout(predicate::str::contains("Dry-running"))
            .stdout(predicate::str::contains("dry run"));
    }

    #[test]
    fn process_dry_run_no_files_modified() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac"]);
        let policy = env.write_policy("test", TEST_POLICY);
        let file = env.media_dir().join("basic-h264-aac.mp4");

        let before = std::fs::read(&file).unwrap();

        env.voom()
            .args([
                "process",
                env.media_dir().to_str().unwrap(),
                "--policy",
                policy.to_str().unwrap(),
                "--dry-run",
            ])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        let after = std::fs::read(&file).unwrap();
        assert_eq!(before, after, "dry-run must not modify files");
    }

    #[test]
    fn process_live_with_mkvtoolnix() {
        require_tool!("ffprobe");
        require_tool!("mkvmerge");
        require_tool!("mkvpropedit");
        let env = TestEnv::new();
        env.populate_media(&["hevc-surround"]);
        let policy = env.write_policy("test", TEST_POLICY);

        env.voom()
            .args([
                "process",
                env.media_dir().to_str().unwrap(),
                "--policy",
                policy.to_str().unwrap(),
                "--no-backup",
            ])
            .timeout(std::time::Duration::from_secs(120))
            .assert()
            .success()
            .stdout(predicate::str::contains("Applying"));
    }

    #[test]
    fn process_empty_directory() {
        let env = TestEnv::new();
        std::fs::create_dir_all(env.media_dir()).unwrap();
        let policy = env.write_policy("test", TEST_POLICY);

        env.voom()
            .args([
                "process",
                env.media_dir().to_str().unwrap(),
                "--policy",
                policy.to_str().unwrap(),
            ])
            .assert()
            .success()
            .stdout(predicate::str::contains("No media files found"));
    }

    #[test]
    fn process_invalid_policy_fails() {
        let env = TestEnv::new();
        std::fs::create_dir_all(env.media_dir()).unwrap();
        let bad = env.write_policy("bad", "not valid voom");

        env.voom()
            .args([
                "process",
                env.media_dir().to_str().unwrap(),
                "--policy",
                bad.to_str().unwrap(),
            ])
            .assert()
            .failure();
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_report
// ═══════════════════════════════════════════════════════════════════════════

mod test_report {
    use super::*;

    #[test]
    fn report_on_empty_db() {
        let env = TestEnv::new();
        env.voom()
            .arg("report")
            .assert()
            .success()
            .stdout(predicate::str::contains("No files in database"));
    }

    #[test]
    fn report_json_after_scan() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac"]);

        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        let output = env
            .voom()
            .args(["report", "--format", "json"])
            .output()
            .expect("run report");

        assert!(output.status.success());
        let stdout = String::from_utf8_lossy(&output.stdout);
        let json: serde_json::Value =
            serde_json::from_str(&stdout).expect("report --format json should produce valid JSON");
        assert!(json["total_files"].as_u64().unwrap() > 0);
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_db
// ═══════════════════════════════════════════════════════════════════════════

mod test_db {
    use super::*;

    #[test]
    fn db_vacuum_on_empty_db() {
        let env = TestEnv::new();
        env.voom().args(["db", "vacuum"]).assert().success();
    }

    #[test]
    fn db_prune_after_file_deletion() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac", "hevc-surround"]);

        // Scan to populate DB
        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        // Delete one file
        std::fs::remove_file(env.media_dir().join("basic-h264-aac.mp4")).unwrap();

        // Prune
        env.voom().args(["db", "prune"]).assert().success();

        // Status should show 1 file
        env.voom()
            .arg("status")
            .assert()
            .success()
            .stdout(predicate::str::contains("1 files"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_status
// ═══════════════════════════════════════════════════════════════════════════

mod test_status {
    use super::*;

    #[test]
    fn status_on_fresh_install() {
        let env = TestEnv::new();
        env.voom()
            .arg("status")
            .assert()
            .success()
            .stdout(predicate::str::contains("VOOM Status"))
            .stdout(predicate::str::contains("0 files"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_jobs
// ═══════════════════════════════════════════════════════════════════════════

mod test_jobs {
    use super::*;

    #[test]
    fn jobs_list_empty() {
        let env = TestEnv::new();
        env.voom().args(["jobs", "list"]).assert().success();
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_policy
// ═══════════════════════════════════════════════════════════════════════════

mod test_policy {
    use super::*;

    fn fixture_path(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../crates/voom-dsl/tests/fixtures")
            .join(name)
    }

    #[test]
    fn policy_validate_valid() {
        let env = TestEnv::new();
        let fixture = fixture_path("production-normalize.voom");
        assert!(fixture.exists());

        env.voom()
            .args(["policy", "validate", fixture.to_str().unwrap()])
            .assert()
            .success()
            .stdout(predicate::str::contains("OK"));
    }

    #[test]
    fn policy_validate_invalid() {
        let env = TestEnv::new();
        let bad = env.write_policy("bad", "garbage syntax");

        env.voom()
            .args(["policy", "validate", bad.to_str().unwrap()])
            .assert()
            .failure();
    }

    #[test]
    fn policy_show_compiled() {
        let env = TestEnv::new();
        let fixture = fixture_path("production-normalize.voom");

        env.voom()
            .args(["policy", "show", fixture.to_str().unwrap()])
            .assert()
            .success()
            .stdout(predicate::str::contains("production-normalize"));
    }

    #[test]
    fn policy_format_roundtrip() {
        let env = TestEnv::new();
        let fixture = fixture_path("production-normalize.voom");
        let copy = env.voom_dir.join("format-test.voom");
        std::fs::copy(&fixture, &copy).unwrap();

        env.voom()
            .args(["policy", "format", copy.to_str().unwrap()])
            .assert()
            .success();

        // Formatted file should still validate
        env.voom()
            .args(["policy", "validate", copy.to_str().unwrap()])
            .assert()
            .success();
    }

    #[test]
    fn policy_validate_full_pipeline() {
        let env = TestEnv::new();
        let fixture = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../docs/examples/full-pipeline.voom");

        env.voom()
            .args(["policy", "validate", fixture.to_str().unwrap()])
            .assert()
            .success()
            .stdout(predicate::str::contains("OK"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_plugin
// ═══════════════════════════════════════════════════════════════════════════

mod test_plugin {
    use super::*;

    #[test]
    fn plugin_list_shows_native() {
        let env = TestEnv::new();
        env.voom()
            .args(["plugin", "list"])
            .assert()
            .success()
            .stdout(predicate::str::contains("sqlite-store"))
            .stdout(predicate::str::contains("discovery"));
    }

    #[test]
    fn plugin_list_shows_descriptions() {
        let env = TestEnv::new();
        env.voom()
            .args(["plugin", "list"])
            .assert()
            .success()
            .stdout(predicate::str::contains("Description"));
    }

    #[test]
    fn plugin_info_shows_metadata() {
        let env = TestEnv::new();
        env.voom()
            .args(["plugin", "info", "sqlite-store"])
            .assert()
            .success()
            .stdout(predicate::str::contains("Plugin:"))
            .stdout(predicate::str::contains("Version:"))
            .stdout(predicate::str::contains("Status:"))
            .stdout(predicate::str::contains("Capabilities:"));
    }

    #[test]
    fn plugin_info_unknown_fails() {
        let env = TestEnv::new();
        env.voom()
            .args(["plugin", "info", "nonexistent-plugin"])
            .assert()
            .failure()
            .stderr(predicate::str::contains("not found"));
    }

    #[test]
    fn plugin_disable_and_enable() {
        let env = TestEnv::new();
        env.voom()
            .args(["plugin", "disable", "backup-manager"])
            .assert()
            .success();

        env.voom()
            .args(["plugin", "enable", "backup-manager"])
            .assert()
            .success();
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_report (--issues)
// ═══════════════════════════════════════════════════════════════════════════

mod test_report_issues {
    use super::*;

    #[test]
    fn report_issues_on_empty_db() {
        let env = TestEnv::new();
        env.voom()
            .args(["report", "--issues"])
            .assert()
            .success()
            .stdout(predicate::str::contains("No files in database"));
    }

    #[test]
    fn report_issues_no_violations_after_scan() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac"]);

        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        env.voom()
            .args(["report", "--issues"])
            .assert()
            .success()
            .stdout(predicate::str::contains(
                "No files with safeguard violations",
            ));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_config
// ═══════════════════════════════════════════════════════════════════════════

mod test_config {
    use super::*;

    #[test]
    fn config_show() {
        let env = TestEnv::new();
        env.voom()
            .args(["config", "show"])
            .assert()
            .success()
            .stdout(predicate::str::contains("data_dir"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// test_workflow — multi-step end-to-end scenarios
// ═══════════════════════════════════════════════════════════════════════════

mod test_workflow {
    use super::*;

    /// Full lifecycle: init → scan → inspect → process --dry-run → report → status
    #[test]
    fn full_lifecycle_dry_run() {
        require_tool!("ffprobe");
        let env = TestEnv::new();

        // Remove config dir to test init
        std::fs::remove_dir_all(&env.voom_dir).unwrap();

        // 1. Init
        env.voom().arg("init").assert().success();

        // 2. Populate media
        env.populate_media(&["hevc-surround", "basic-h264-aac"]);

        // 3. Scan
        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success()
            .stdout(predicate::str::contains("2 files discovered"));

        // 4. Inspect (should hit DB)
        let mkv = env.media_dir().join("hevc-surround.mkv");
        env.voom()
            .args(["inspect", mkv.to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(30))
            .assert()
            .success();

        // 5. Process dry-run with the starter policy from init
        let starter = env.voom_dir.join("policies/default.voom");
        assert!(starter.exists(), "init should create default.voom");
        env.voom()
            .args([
                "process",
                env.media_dir().to_str().unwrap(),
                "--policy",
                starter.to_str().unwrap(),
                "--dry-run",
            ])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success()
            .stdout(predicate::str::contains("dry run"));

        // 6. Report
        env.voom()
            .arg("report")
            .assert()
            .success()
            .stdout(predicate::str::contains("2 files"));

        // 7. Status
        env.voom()
            .arg("status")
            .assert()
            .success()
            .stdout(predicate::str::contains("2 files"));
    }

    /// Scan → delete file → prune → verify status
    #[test]
    fn scan_prune_rescan() {
        require_tool!("ffprobe");
        let env = TestEnv::new();
        env.populate_media(&["basic-h264-aac", "hevc-surround"]);

        // Scan
        env.voom()
            .args(["scan", env.media_dir().to_str().unwrap()])
            .timeout(std::time::Duration::from_secs(60))
            .assert()
            .success();

        // Delete one file
        std::fs::remove_file(env.media_dir().join("basic-h264-aac.mp4")).unwrap();

        // Prune
        env.voom().args(["db", "prune"]).assert().success();

        // Status should show 1 file
        env.voom()
            .arg("status")
            .assert()
            .success()
            .stdout(predicate::str::contains("1 files"));
    }
}
